### ISSUE TITLE
Updating protobuf dependency

### ISSUE THREAD

**Issue by aemmitt-ns** [nccgroup/blackboxprotobuf#11]
Would it be possible to update the protobuf dependency in the pypi package? It is currently at `protobuf==3.10.0` but it would be better to bring it up to at least `protobuf==3.14.0`. This causes no issues and would resolve conflicts with current versions of mitmproxy which uses this version. Sorry if this is not the proper place for this request

**Comment by rwinkelmaier-ncc** [comment]
Hi,

There is currently no official pypi package for blackboxprotobuf. The package currently there is an older fork. I do hope to have an official package published soon, but in the meantime, there is a package specification in https://github.com/nccgroup/blackboxprotobuf/tree/master/lib if that helps.

If you're using python3, the dependency specification should be compatible with protobuf 3.14. For python2.7 I think it's set to 3.17.3 exactly since that's the last version to support python2.7 I think. That requirement could probably be loosened to allow older versions if needed.
