### ISSUE TITLE
Root logger

### ISSUE THREAD

**Issue by liearka** [nccgroup/blackboxprotobuf#43]
Hi!
I noticed that library uses root logger. So there is no covenient way to turn off logs from the library without turning off logs of your app if it also uses root logger. And there could be a lot of messages like https://github.com/nccgroup/blackboxprotobuf/blob/master/lib/blackboxprotobuf/lib/types/length_delim.py#L591 which make logs unreadable...
I use the version of library for python 2 (legacy thing) and can not even dream about this issue to be fixed. But I will be glad to see that this will be corrected at least for other users...

**Comment by rwinkelmaier-ncc** [comment]
Thanks for calling this out. I added module loggers to each module in https://github.com/nccgroup/blackboxprotobuf/commit/cd03d5c86fb57c8d1e264e57f80a446a98a2da8e. Let me know if this fixes the issue.

Regarding python2, the most recent version of the library should still be compatible with python2, as that is what is used in Burp (technically Jython2) and I do run the tests using both python2 and python3. Off the top of my head, the two exceptions might be the CLI (`__main__.py`) and the mitm addon.

IIRC I stopped adding python2 compatibility when pushing to pypi because the tooling didn't handle it well and it complicated the dependencies, but you can still use the latest bbpb from source or with a manual install. I may revisit publishing for python2 at some point since the `protobuf` dependency is gone, but not sure when that will be.
